version: '3.7'
services:

  mongo:
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_DATABASE: etaireia
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
  
  traefik:
    image: "traefik:v2.6"
    restart: on-failure
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
    ports:
      - "80:80/tcp"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  frontend:
    build:
      context: ./etaireia
    restart: on-failure
    environment:
      PORT: 3000
    labels:
      - "docker.project=etaireia"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-dev.entrypoints=web"
      - "traefik.http.routers.frontend-dev.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend-dev.loadbalancer.server.port=3000"

  json-server:
    image: clue/json-server
    restart: on-failure
    labels:
      - "docker.project=etaireia"
      - "traefik.enable=true"
      - "traefik.http.routers.json-server.entrypoints=web"
      - "traefik.http.routers.json-server.rule=PathPrefix(`/api/v1`)"
      - "traefik.http.services.json-server.loadbalancer.server.port=80"
      - "traefik.http.middlewares.json-server.stripprefix.prefixes=/api/v1"
    volumes:
      - ./db.json:/data/db.json 

  # backend:
  #   build:
  #     context: ./etaireia-backend
  #   labels:
  #     - "docker.project=etaireia"
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.backend-dev.entrypoints=web"
  #     - "traefik.http.routers.backend-dev.rule=PathPrefix(`/api/`)"
  #     - "traefik.http.services.backend-dev.loadbalancer.server.port=3000"
  #   environment:
  #     PORT: 3000
  #     MONGO_USERNAME: admin
  #     MONGO_PASSWORD: admin
  #     DATABASE_NAME: etaireia
  #     MONGO_URL: mongodb://etaireia-mongo
  #   restart: always
  #   depends_on: 
  #     - etaireia-mongo

volumes:
  mongodb_data_container:
