version: '3.7'
services:

  ds-mongo:
    profiles: ["dev"]
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
    # - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
  
  ds-traefik-prod:
    profiles: ["prod"]
    image: "traefik:v2.6"
    command:
      - "--providers.docker.constraints=Label(`mastrogiovanni.project`,`digital-dignature`)"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--api.insecure=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=michele.mastrogiovanni@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443/tcp"
      - "8080:8080"
    restart: always
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ds-traefik-dev:
    profiles: ["dev"]
    image: "traefik:v2.6"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
    ports:
      - "80:80/tcp"
      - "8080:8080"
    restart: always
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  ds-backend-prod:
    profiles: ["prod"]
    build:
      context: ./digital-signature-backend
    labels:
      - "mastrogiovanni.project=digital-dignature"
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.routers.backend.rule=Host(`${NODE_HOST}`) && PathPrefix(`/api/`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    environment:
      PORT: 3000
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_URL: ${MONGO_URL}

    restart: always
    depends_on: 
      - ds-traefik-prod

  ds-backend-dev:
    profiles: ["dev"]
    build:
      context: ./digital-signature-backend
    labels:
      - "mastrogiovanni.project=digital-dignature"
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    environment:
      PORT: 3000
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_URL: mongodb://ds-mongo
    restart: always
    depends_on: 
      - ds-mongo
      - ds-traefik-dev

  ds-frontend-prod:
    profiles: ["prod"]
    build:
      context: ./digital-signature
    labels:
      - "mastrogiovanni.project=digital-dignature"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.frontend.rule=Host(`${NODE_HOST}`) && PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    environment:
      PORT: 3000
    restart: on-failure
    # command: node dist/index.js setup-api
    depends_on: 
      - ds-traefik-prod

  ds-frontend-dev:
    profiles: ["dev"]
    build:
      context: ./digital-signature
    labels:
      - "mastrogiovanni.project=digital-dignature"
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    environment:
      PORT: 3000
    restart: on-failure
    # command: node dist/index.js setup-api
    depends_on: 
      - ds-mongo
      - ds-traefik-dev

volumes:
  mongodb_data_container:
